name: CI

on: 
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 14

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint


  test-app:
    name: Test app
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
